from typing import Any, Optional
from tkinter import Misc

class Style: ...
class Window(Misc): ...
class Label(Misc):
    def __init__(self, master: Optional[Misc] = ..., *args: Any, **kwargs: Any) -> None: ...
class Button(Misc):
    def __init__(self, master: Optional[Misc] = ..., *args: Any, **kwargs: Any) -> None: ...
class Entry(Misc):
    def __init__(self, master: Optional[Misc] = ..., *args: Any, **kwargs: Any) -> None: ...
class Treeview(Misc):
    def __init__(self, master: Optional[Misc] = ..., *args: Any, **kwargs: Any) -> None: ...
