"""Type stubs for ttkbootstrap library.

This stub file provides minimal type hints for ttkbootstrap widgets and components
used in the RC Gestor project. It focuses on reducing false positives from Pyright
by covering the API surface actually used by our codebase.

Generated for CompatPack-02 on 2025-11-13.
"""

from typing import Any, Callable, Sequence
from tkinter import Misc, Widget, Wm
from tkinter.font import Font

# Style management
class Style:
    """ttkbootstrap Style manager."""

    def __init__(self, theme: str | None = None) -> None: ...
    def theme_use(self, themename: str | None = None) -> str: ...
    def theme_names(self) -> list[str]: ...
    def configure(self, style: str, **kwargs: Any) -> Any: ...

# Window class (extends Misc with common window methods)
class Window(Misc):
    """ttkbootstrap Window class."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

# Base widget types with ttkbootstrap extensions
class Frame(Misc):
    """ttkbootstrap Frame widget."""

    def __init__(self, master: Misc | None = None, *, padding: int | tuple[int, ...] | None = None, bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def pack_forget(self) -> None: ...
    def grid_forget(self) -> None: ...
    def place_forget(self) -> None: ...

class Label(Misc):
    """ttkbootstrap Label widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        text: str = "",
        textvariable: Any = None,
        font: Font | str | tuple[str, int] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def cget(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...

class Button(Misc):
    """ttkbootstrap Button widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        text: str = "",
        command: Callable[[], Any] | None = None,
        state: str = "normal",
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def invoke(self) -> Any: ...

class Entry(Misc):
    """ttkbootstrap Entry widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        textvariable: Any = None,
        width: int | None = None,
        state: str = "normal",
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def insert(self, index: int | str, string: str) -> None: ...
    def delete(self, first: int | str, last: int | str | None = None) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...

class Text(Misc):
    """ttkbootstrap Text widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        width: int | None = None,
        height: int | None = None,
        state: str = "normal",
        wrap: str = "char",
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self, start: str, end: str | None = None) -> str: ...
    def insert(self, index: str, chars: str, *tags: str) -> None: ...
    def delete(self, start: str, end: str | None = None) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...

class Toplevel(Wm, Misc):
    """ttkbootstrap Toplevel window."""

    def __init__(self, master: Misc | None = None, *, bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def wm_transient(self, master: Misc | str | None = None) -> str: ...
    def wm_attributes(self, *args: Any) -> Any: ...
    def wm_title(self, string: str | None = None) -> str: ...
    def wm_geometry(self, newGeometry: str | None = None) -> str: ...
    def grab_set(self) -> None: ...
    def grab_release(self) -> None: ...
    def focus_set(self) -> None: ...
    def after(self, ms: int, func: Callable[[], Any] | None = None, *args: Any) -> str: ...

class Canvas(Misc):
    """ttkbootstrap Canvas widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        width: int | None = None,
        height: int | None = None,
        scrollregion: tuple[int, int, int, int] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def create_window(self, x: float, y: float, **kwargs: Any) -> int: ...
    def configure(self, **kwargs: Any) -> None: ...
    def yview_moveto(self, fraction: float) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...

class Scrollbar(Misc):
    """ttkbootstrap Scrollbar widget."""

    def __init__(
        self, master: Misc | None = None, *, orient: str = "vertical", command: Callable[..., Any] | None = None, bootstyle: str | None = None, **kwargs: Any
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def set(self, first: float, last: float) -> None: ...

class Checkbutton(Misc):
    """ttkbootstrap Checkbutton widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        text: str = "",
        variable: Any = None,
        command: Callable[[], Any] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def invoke(self) -> Any: ...

class Radiobutton(Misc):
    """ttkbootstrap Radiobutton widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        text: str = "",
        variable: Any = None,
        value: Any = None,
        command: Callable[[], Any] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def invoke(self) -> Any: ...

class Combobox(Misc):
    """ttkbootstrap Combobox widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        textvariable: Any = None,
        values: Sequence[str] | None = None,
        state: str = "normal",
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def set(self, value: str) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...

class Treeview(Misc):
    """ttkbootstrap Treeview widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        columns: Sequence[str] | None = None,
        show: str = "tree headings",
        selectmode: str = "browse",
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def insert(self, parent: str, index: int | str, iid: str | None = None, **kwargs: Any) -> str: ...
    def delete(self, *items: str) -> None: ...
    def selection(self) -> tuple[str, ...]: ...
    def item(self, item: str, option: str | None = None, **kwargs: Any) -> Any: ...
    def heading(self, column: str, **kwargs: Any) -> None: ...
    def column(self, column: str, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...
    def yview(self, *args: Any) -> Any: ...

class Notebook(Misc):
    """ttkbootstrap Notebook widget."""

    def __init__(self, master: Misc | None = None, *, bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def add(self, child: Widget, **kwargs: Any) -> None: ...
    def tab(self, tab_id: int | str, option: str | None = None, **kwargs: Any) -> Any: ...
    def select(self, tab_id: int | str | None = None) -> str | None: ...
    def configure(self, **kwargs: Any) -> None: ...

class Progressbar(Misc):
    """ttkbootstrap Progressbar widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        orient: str = "horizontal",
        length: int = 100,
        mode: str = "determinate",
        maximum: float = 100.0,
        value: float = 0.0,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def step(self, amount: float = 1.0) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def start(self, interval: int | None = None) -> None: ...
    def stop(self) -> None: ...

class Separator(Misc):
    """ttkbootstrap Separator widget."""

    def __init__(self, master: Misc | None = None, *, orient: str = "horizontal", bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...

class Labelframe(Misc):
    """ttkbootstrap Labelframe widget."""

    def __init__(
        self, master: Misc | None = None, *, text: str = "", padding: int | tuple[int, ...] | None = None, bootstyle: str | None = None, **kwargs: Any
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...

class Spinbox(Misc):
    """ttkbootstrap Spinbox widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        from_: float | None = None,
        to: float | None = None,
        increment: float = 1.0,
        textvariable: Any = None,
        values: Sequence[str] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def configure(self, **kwargs: Any) -> None: ...

class Scale(Misc):
    """ttkbootstrap Scale widget."""

    def __init__(
        self,
        master: Misc | None = None,
        *,
        from_: float = 0.0,
        to: float = 100.0,
        orient: str = "horizontal",
        value: float = 0.0,
        command: Callable[[float], Any] | None = None,
        bootstyle: str | None = None,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> float: ...
    def set(self, value: float) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class Panedwindow(Misc):
    """ttkbootstrap Panedwindow widget."""

    def __init__(self, master: Misc | None = None, *, orient: str = "horizontal", bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def add(self, child: Widget, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class Menu(Misc):
    """ttkbootstrap Menu widget."""

    def __init__(self, master: Misc | None = None, *, bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def add_command(self, **kwargs: Any) -> None: ...
    def add_cascade(self, **kwargs: Any) -> None: ...
    def add_separator(self, **kwargs: Any) -> None: ...
    def add_checkbutton(self, **kwargs: Any) -> None: ...
    def add_radiobutton(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class Menubutton(Misc):
    """ttkbootstrap Menubutton widget."""

    def __init__(self, master: Misc | None = None, *, text: str = "", menu: Menu | None = None, bootstyle: str | None = None, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...

class Listbox(Misc):
    """ttkbootstrap Listbox widget."""

    def __init__(
        self, master: Misc | None = None, *, selectmode: str = "browse", height: int | None = None, bootstyle: str | None = None, **kwargs: Any
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def insert(self, index: int | str, *elements: str) -> None: ...
    def delete(self, first: int | str, last: int | str | None = None) -> None: ...
    def get(self, first: int | str, last: int | str | None = None) -> str | tuple[str, ...]: ...
    def curselection(self) -> tuple[int, ...]: ...
    def configure(self, **kwargs: Any) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = None, add: str | None = None) -> str: ...
