# -*- coding: utf-8 -*-
"""Typing Protocols para os mixins de ClientEditorDialog e ClientFilesDialog.

Criado na Fase 7 para eliminar ~379 warnings do Pyright/Pylance
(reportAttributeAccessIssue) nos mixins, sem alterar comportamento de runtime.

Uso: importado apenas sob TYPE_CHECKING nos mixins para anotar ``self``.
"""

from __future__ import annotations

import queue
import tkinter as tk
from concurrent.futures import ThreadPoolExecutor
from tkinter import ttk
from typing import Any, Callable, Protocol


# ============================================================================
# EditorDialogProto — descreve o "self" esperado pelos editor mixins
# ============================================================================


class EditorDialogProto(Protocol):
    """Protocol mínimo que descreve ClientEditorDialog para os mixins."""

    # -- Atributos de __init__ -----------------------------------------------
    session_id: str
    client_id: int | None
    on_save: Callable[[dict[str, Any]], None] | None
    on_close: Callable[[], None] | None
    _client_data: dict[str, Any] | None
    _setup_modal_job: str | None
    _placeholder_job: str | None

    # -- Widgets criados em EditorUIMixin._build_ui --------------------------
    razao_entry: Any  # ctk.CTkEntry
    cnpj_entry: Any  # ctk.CTkEntry
    nome_entry: Any  # ctk.CTkEntry
    whatsapp_entry: Any  # ctk.CTkEntry
    obs_text: Any  # ctk.CTkTextbox
    contatos_text: Any  # ctk.CTkTextbox
    status_var: tk.StringVar
    status_combo: Any  # ctk.CTkOptionMenu
    save_btn: Any  # ctk.CTkButton
    cancel_btn: Any  # ctk.CTkButton
    senhas_btn: Any  # ctk.CTkButton
    arquivos_btn: Any  # ctk.CTkButton
    cartao_btn: Any  # ctk.CTkButton
    upload_btn: Any  # ctk.CTkButton
    endereco_entry: Any  # ctk.CTkEntry
    bairro_entry: Any  # ctk.CTkEntry
    cidade_entry: Any  # ctk.CTkEntry
    cep_entry: Any  # ctk.CTkEntry
    _right_spacer: Any  # ctk.CTkFrame
    _status_container: Any  # ctk.CTkFrame
    table: Any  # referência à tabela (se existir)

    # -- Métodos cruzados entre mixins ---------------------------------------
    def _build_ui(self) -> None: ...
    def _build_left_panel(self, parent: Any) -> None: ...
    def _build_right_panel(self, parent: Any) -> None: ...
    def _build_buttons(self, parent: Any) -> None: ...
    def _set_entry_value(self, entry: Any, value: str) -> None: ...
    def _activate_placeholder(self, entry: Any) -> None: ...
    def _sync_right_spacer_height(self) -> None: ...
    def _load_client_data(self) -> None: ...
    def _parse_contatos_from_textbox(self) -> list[dict[str, Any]]: ...
    def _load_contatos_from_db(self, cliente_id: int) -> None: ...
    def _save_contatos_to_db(self, cliente_id: int) -> None: ...
    def _validate_fields(self) -> bool: ...
    def _on_save_clicked(self) -> None: ...
    def _on_cnpj_focus_out(self, event: Any = ...) -> None: ...
    def _on_whatsapp_focus_out(self, event: Any = ...) -> None: ...
    def _on_return_key(self, event: Any) -> str: ...
    def _on_cancel(self) -> None: ...
    def _on_senhas(self) -> None: ...
    def _on_arquivos(self) -> None: ...
    def _on_cartao_cnpj(self) -> None: ...
    def _on_enviar_documentos(self) -> None: ...
    def _set_window_title(self) -> None: ...
    def _cleanup_and_destroy(self) -> None: ...

    # -- Métodos herdados de CTkToplevel / tkinter.Misc ----------------------
    def after(self, ms: int, func: Any = ..., *args: Any) -> str: ...
    def after_idle(self, func: Any, *args: Any) -> str: ...
    def after_cancel(self, id: str) -> None: ...  # noqa: A002
    def bind(self, sequence: str, func: Any = ..., add: str = ...) -> str: ...
    def configure(self, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def focus_get(self) -> tk.Misc | None: ...
    def grab_set(self) -> None: ...
    def grab_release(self) -> None: ...
    def protocol(self, name: str, func: Any = ...) -> str: ...
    def title(self, string: str = ...) -> str: ...
    def update_idletasks(self) -> None: ...
    def winfo_exists(self) -> bool: ...
    def winfo_reqwidth(self) -> int: ...
    def winfo_reqheight(self) -> int: ...

    # -- Métodos de grid (usados na construção de UI) ------------------------
    def grid_info(self) -> dict[str, Any]: ...
    def grid_propagate(self, flag: bool = ...) -> bool | None: ...


# ============================================================================
# FilesDialogProto — descreve o "self" esperado pelos files mixins
# ============================================================================


class FilesDialogProto(Protocol):
    """Protocol mínimo que descreve ClientFilesDialog para os mixins."""

    # -- Atributos de __init__ -----------------------------------------------
    client_id: int
    client_name: str
    razao_social: str
    cnpj: str
    supabase: Any
    _files: list[dict[str, Any]]
    _org_id: str
    _loading: bool
    _current_thread: Any
    _nav_stack: list[str]
    _tree_metadata: dict[str, dict[str, Any]]
    _progress_queue: queue.Queue[dict[str, Any]]
    _tree_colors: Any
    _executor: ThreadPoolExecutor | None
    _closing: bool
    _after_ids: set[str]
    _img_pdf: Any
    _img_file: Any

    # -- Widgets criados em FilesUIMixin._build_ui ---------------------------
    btn_back: Any  # ctk.CTkButton
    btn_upload: Any  # ctk.CTkButton
    btn_baixar: Any  # ctk.CTkButton
    btn_baixar_zip: Any  # ctk.CTkButton
    btn_visualizar: Any  # ctk.CTkButton
    btn_excluir: Any  # ctk.CTkButton
    breadcrumb_label: Any  # ctk.CTkLabel
    status_label: Any  # ctk.CTkLabel
    progress_bar: Any  # ctk.CTkProgressBar
    _dl_card: Any  # ctk.CTkFrame
    _dl_name_label: Any  # ctk.CTkLabel
    _dl_pct_label: Any  # ctk.CTkLabel
    _header_left_label: Any  # ctk.CTkLabel
    _tree_container: Any  # CTkTreeviewContainer
    tree: ttk.Treeview

    # -- Métodos cruzados entre mixins ---------------------------------------
    def _build_ui(self) -> None: ...
    def _safe_after(self, ms: int, callback: Any) -> str | None: ...
    def _ui_alive(self) -> bool: ...
    def _safe_close(self) -> None: ...
    def _cancel_afters(self) -> None: ...
    def _shutdown_executor(self) -> None: ...
    def _format_size(self, size: int) -> str: ...
    # UI mixin
    _TITLE_MAX_LEN: int
    def _show_progress(self, value: float = ...) -> None: ...
    def _hide_progress(self) -> None: ...
    def _update_progress(self, value: float) -> None: ...
    def _set_smart_title(self) -> None: ...
    def _on_header_configure(self, _event: Any = ...) -> None: ...
    def _poll_progress_queue(self) -> None: ...
    def _update_button_states(self) -> None: ...
    def _update_breadcrumb(self) -> None: ...
    def _update_back_button(self) -> None: ...
    def _update_status(self, text: str) -> None: ...
    def _disable_buttons(self) -> None: ...
    def _enable_buttons(self) -> None: ...
    # Navigation mixin
    def _refresh_files(self) -> None: ...
    def _render_tree(self) -> None: ...
    def _render_files(self) -> None: ...
    def _navigate_to_folder(self, folder: str) -> None: ...
    def _get_selected_item(self) -> dict[str, Any] | None: ...
    def _on_tree_double_click(self, event: Any) -> None: ...
    def _on_tree_selection_change(self, event: Any = ...) -> None: ...
    def _on_back(self) -> None: ...
    def _copy_breadcrumb(self) -> None: ...
    def _on_files_loaded(self, files: list[dict[str, Any]]) -> None: ...
    def _on_load_error(self, error: str) -> None: ...
    # Upload mixin
    def _on_upload(self) -> None: ...
    def _upload_files(self, file_paths: Any, subfolder: str) -> None: ...
    def _on_upload_complete(self, count: int) -> None: ...
    def _on_upload_error(self, error: str) -> None: ...
    def _on_excluir(self) -> None: ...
    def _on_delete_file_from_metadata(self, metadata: dict[str, Any]) -> None: ...
    def _on_delete_folder(self, metadata: dict[str, Any]) -> None: ...
    def _on_delete_folder_complete(self, folder_name: str, count: int) -> None: ...
    def _on_delete_folder_empty(self, folder_name: str) -> None: ...
    def _on_delete_complete(self, file_name: str) -> None: ...
    def _on_delete_error(self, error: str) -> None: ...
    # Download mixin
    def _on_baixar(self) -> None: ...
    def _on_baixar_pasta_zip(self) -> None: ...
    def _on_visualizar(self) -> None: ...
    def _on_open_file_from_metadata(self, metadata: dict[str, Any]) -> None: ...
    def _on_download_file_from_metadata(self, metadata: dict[str, Any]) -> None: ...
    def _on_open_complete(self, file_name: str) -> None: ...
    def _on_open_error(self, error: str) -> None: ...
    def _on_download_complete(self, file_name: str, save_path: str) -> None: ...
    def _on_download_error(self, error: str) -> None: ...
    def _download_folder_as_zip(self, folder_prefix: str, save_path: str) -> None: ...
    def _on_download_zip_complete(self, file_count: int, save_path: str) -> None: ...
    def _on_download_zip_error(self, error: str) -> None: ...

    # -- Métodos herdados de CTkToplevel / tkinter.Misc ----------------------
    def after(self, ms: int, func: Any = ..., *args: Any) -> str: ...
    def after_cancel(self, id: str) -> None: ...  # noqa: A002
    def bind(self, sequence: str, func: Any = ..., add: str = ...) -> str: ...
    def clipboard_clear(self) -> None: ...
    def clipboard_append(self, string: str) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def grid_columnconfigure(self, index: Any, **kwargs: Any) -> None: ...
    def grid_rowconfigure(self, index: Any, **kwargs: Any) -> None: ...
    def grid_remove(self) -> None: ...
    def protocol(self, name: str, func: Any = ...) -> str: ...
    def title(self, string: str = ...) -> str: ...
    def wait_window(self, window: Any = ...) -> None: ...
    def winfo_exists(self) -> bool: ...
    def winfo_ismapped(self) -> bool: ...
    def winfo_reqwidth(self) -> int: ...

    # -- master (parent widget) ----------------------------------------------
    @property
    def master(self) -> Any: ...

    # -- minsize (from Wm) ---------------------------------------------------
    def minsize(self, width: int = ..., height: int = ...) -> tuple[int, int] | None: ...
