# -*- coding: utf-8 -*-
"""Typing Protocols para os mixins de ClientEditorDialog.

Criado na Fase 7 para eliminar ~379 warnings do Pyright/Pylance
(reportAttributeAccessIssue) nos mixins, sem alterar comportamento de runtime.

Uso: importado apenas sob TYPE_CHECKING nos mixins para anotar ``self``.
"""

from __future__ import annotations

import tkinter as tk
from typing import Any, Callable, Protocol


# ============================================================================
# EditorDialogProto — descreve o "self" esperado pelos editor mixins
# ============================================================================


class EditorDialogProto(Protocol):
    """Protocol mínimo que descreve ClientEditorDialog para os mixins."""

    # -- Atributos de __init__ -----------------------------------------------
    session_id: str
    client_id: int | None
    on_save: Callable[[dict[str, Any]], None] | None
    on_close: Callable[[], None] | None
    _client_data: dict[str, Any] | None
    _setup_modal_job: str | None
    _placeholder_job: str | None

    # -- Widgets criados em EditorUIMixin._build_ui --------------------------
    razao_entry: Any  # ctk.CTkEntry
    cnpj_entry: Any  # ctk.CTkEntry
    nome_entry: Any  # ctk.CTkEntry
    whatsapp_entry: Any  # ctk.CTkEntry
    obs_text: Any  # ctk.CTkTextbox
    contatos_text: Any  # ctk.CTkTextbox
    bloco_notas_text: Any  # ctk.CTkTextbox
    status_var: tk.StringVar
    status_combo: Any  # ctk.CTkOptionMenu
    save_btn: Any  # ctk.CTkButton
    cancel_btn: Any  # ctk.CTkButton
    arquivos_btn: Any  # ctk.CTkButton
    cartao_btn: Any  # ctk.CTkButton
    upload_btn: Any  # ctk.CTkButton
    table: Any  # referência à tabela (se existir)

    # -- Métodos cruzados entre mixins ---------------------------------------
    def _build_ui(self) -> None: ...
    def _build_left_panel(self, parent: Any) -> None: ...
    def _build_right_panel(self, parent: Any) -> None: ...
    def _build_buttons(self, parent: Any) -> None: ...
    def _set_entry_value(self, entry: Any, value: str) -> None: ...
    def _activate_placeholder(self, entry: Any) -> None: ...
    def _load_client_data(self) -> None: ...
    def _parse_contatos_from_textbox(self) -> list[dict[str, Any]]: ...
    def _run_in_thread(
        self,
        work: Callable[..., Any],
        on_success: Callable[[Any], None] | None = ...,
        on_error: Callable[[Exception], None] | None = ...,
    ) -> None: ...
    def _load_contatos_from_db(self, cliente_id: int) -> None: ...
    def _save_contatos_to_db(self, cliente_id: int, *, on_done: Callable[[], None] | None = ...) -> None: ...
    def _load_bloco_notas_from_db(self, cliente_id: int) -> None: ...
    def _save_bloco_notas_to_db(self, cliente_id: int, *, on_done: Callable[[], None] | None = ...) -> None: ...
    def _validate_fields(self) -> bool: ...
    def _on_save_clicked(self) -> None: ...
    def _on_cnpj_focus_out(self, event: Any = ...) -> None: ...
    def _on_whatsapp_focus_out(self, event: Any = ...) -> None: ...
    def _on_return_key(self, event: Any) -> str: ...
    def _on_cancel(self) -> None: ...
    def _on_arquivos(self) -> None: ...
    def _on_cartao_cnpj(self) -> None: ...
    def _on_enviar_documentos(self) -> None: ...
    def _set_window_title(self) -> None: ...
    def _cleanup_and_destroy(self) -> None: ...

    # -- Métodos herdados de CTkToplevel / tkinter.Misc ----------------------
    def after(self, ms: int, func: Any = ..., *args: Any) -> str: ...
    def after_idle(self, func: Any, *args: Any) -> str: ...
    def after_cancel(self, id: str) -> None: ...  # noqa: A002
    def bind(self, sequence: str, func: Any = ..., add: str = ...) -> str: ...
    def configure(self, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def focus_get(self) -> tk.Misc | None: ...
    def grab_set(self) -> None: ...
    def grab_release(self) -> None: ...
    def protocol(self, name: str, func: Any = ...) -> str: ...
    def title(self, string: str = ...) -> str: ...
    def update_idletasks(self) -> None: ...
    def winfo_exists(self) -> bool: ...
    def winfo_reqwidth(self) -> int: ...
    def winfo_reqheight(self) -> int: ...

    # -- Métodos de grid (usados na construção de UI) ------------------------
    def grid_info(self) -> dict[str, Any]: ...
    def grid_propagate(self, flag: bool = ...) -> bool | None: ...
