COL_ID_WIDTH        = 60
COL_RAZAO_WIDTH     = 320   # vai esticar
COL_CNPJ_WIDTH      = 150
COL_NOME_WIDTH      = 180
COL_WHATSAPP_WIDTH  = 130
COL_OBS_WIDTH       = 330   # vai esticar
COL_ULTIMA_WIDTH    = 200
