"""Type stubs for customtkinter library (minimal coverage for RC Gestor).

This stub file provides type hints for customtkinter widgets and methods used
in the project to eliminate Pylance reportMissingTypeStubs warnings.

Created for Microfase 7 (Clientes) - 2026-01-14.

Note: This is a minimal stub covering only the subset of customtkinter used in RC Gestor.
Extend this file as new widgets/methods are introduced.
"""

from typing import Any, Callable, Literal, Protocol, runtime_checkable
from tkinter import Misc

# Type aliases
Anchor = Literal["n", "s", "e", "w", "ne", "nw", "se", "sw", "center"]
Corner = Literal["topleft", "topright", "bottomleft", "bottomright"]

@runtime_checkable
class CTkBaseClass(Protocol):
    """Base protocol for CustomTkinter widgets.

    Este protocol define a interface comum de todos os widgets CustomTkinter,
    garantindo compatibilidade com SupportsCgetConfigure (Microfase 9) e
    prevenindo regressões de tipagem (Microfase 10).
    """
    def configure(self, **kwargs: Any) -> None: ...
    def cget(self, key: str) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...  # Equivalente a cget
    def bind(self, sequence: str, func: Callable[..., Any] | None = ..., add: str | None = ...) -> str: ...
    def unbind(self, sequence: str, funcid: str | None = ...) -> None: ...
    def destroy(self) -> None: ...
    def focus_set(self) -> None: ...
    def focus(self) -> None: ...
    def grab_set(self) -> None: ...
    def grab_release(self) -> None: ...
    def winfo_exists(self) -> bool: ...
    def winfo_width(self) -> int: ...
    def winfo_height(self) -> int: ...
    def update(self) -> None: ...
    def update_idletasks(self) -> None: ...
    def after(self, ms: int, func: Callable[..., Any] | None = ..., *args: Any) -> str: ...
    def after_cancel(self, id: str) -> None: ...  # noqa: A002

class CTk(Misc):
    """CustomTkinter main window (root)."""
    def __init__(self, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def title(self, string: str | None = ...) -> str | None: ...
    def geometry(self, newGeometry: str | None = ...) -> str | None: ...  # noqa: N803
    def configure(self, **kwargs: Any) -> None: ...
    def mainloop(self) -> None: ...
    def protocol(self, name: str, func: Callable[[], Any] | None = ...) -> str | None: ...
    def wm_attributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def iconbitmap(self, bitmap: str | None = ..., default: str | None = ...) -> str | None: ...
    def withdraw(self) -> None: ...
    def deiconify(self) -> None: ...
    def focus_set(self) -> None: ...

class CTkToplevel(Misc):
    """CustomTkinter toplevel window."""
    def __init__(self, master: Misc | None = ..., **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def title(self, string: str | None = ...) -> str | None: ...
    def geometry(self, newGeometry: str | None = ...) -> str | None: ...  # noqa: N803
    def configure(self, **kwargs: Any) -> None: ...
    def grab_set(self) -> None: ...
    def grab_release(self) -> None: ...
    def focus_set(self) -> None: ...
    def protocol(self, name: str, func: Callable[[], Any] | None = ...) -> str | None: ...
    def transient(self, master: Misc | None = ...) -> str | None: ...
    def wm_transient(self, master: Misc | None = ...) -> str | None: ...
    def attributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def wm_attributes(self, *args: Any, **kwargs: Any) -> Any: ...
    def after(self, ms: int, func: Callable[..., Any] | None = ..., *args: Any) -> str: ...
    def bind(self, sequence: str, func: Callable[..., Any] | None = ..., add: str | None = ...) -> str: ...
    def update_idletasks(self) -> None: ...
    def wait_window(self, window: Misc | None = ...) -> None: ...
    def resizable(self, width: bool = ..., height: bool = ...) -> None: ...
    def winfo_reqwidth(self) -> int: ...
    def winfo_reqheight(self) -> int: ...
    def winfo_screenwidth(self) -> int: ...
    def winfo_screenheight(self) -> int: ...

class CTkFrame(CTkBaseClass):
    """CustomTkinter frame container."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def pack_forget(self) -> None: ...
    def grid_forget(self) -> None: ...
    def place_forget(self) -> None: ...
    def columnconfigure(
        self, index: int, weight: int | None = ..., minsize: int | None = ..., pad: int | None = ..., **kw: Any
    ) -> Any: ...
    def rowconfigure(
        self, index: int, weight: int | None = ..., minsize: int | None = ..., pad: int | None = ..., **kw: Any
    ) -> Any: ...

class CTkScrollableFrame(CTkFrame):
    """CustomTkinter scrollable frame."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        scrollbar_fg_color: str | tuple[str, str] | None = ...,
        scrollbar_button_color: str | tuple[str, str] | None = ...,
        scrollbar_button_hover_color: str | tuple[str, str] | None = ...,
        **kwargs: Any,
    ) -> None: ...

class CTkLabel(CTkBaseClass):
    """CustomTkinter label widget."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        text_color_disabled: str | tuple[str, str] | None = ...,
        text: str = ...,
        font: tuple[str, int] | Any = ...,
        image: Any = ...,
        compound: str = ...,
        anchor: Anchor = ...,
        wraplength: int = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...

class CTkEntry(CTkBaseClass):
    """CustomTkinter entry widget."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        placeholder_text_color: str | tuple[str, str] | None = ...,
        textvariable: Any = ...,
        placeholder_text: str | None = ...,
        font: tuple[str, int] | Any = ...,
        show: str | None = ...,
        state: str = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def insert(self, index: int | str, string: str) -> None: ...
    def delete(self, first: int | str, last: int | str | None = ...) -> None: ...

class CTkButton(CTkBaseClass):
    """CustomTkinter button widget."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        border_spacing: int = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        hover_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        text_color_disabled: str | tuple[str, str] | None = ...,
        text: str = ...,
        font: tuple[str, int] | Any = ...,
        image: Any = ...,
        state: str = ...,
        hover: bool = ...,
        command: Callable[[], Any] | None = ...,
        compound: str = ...,
        anchor: Anchor = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def invoke(self) -> Any: ...

class CTkTextbox(CTkBaseClass):
    """CustomTkinter textbox widget (multi-line text)."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        border_spacing: int = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        scrollbar_button_color: str | tuple[str, str] | None = ...,
        scrollbar_button_hover_color: str | tuple[str, str] | None = ...,
        font: tuple[str, int] | Any = ...,
        state: str = ...,
        wrap: str = ...,
        activate_scrollbars: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self, index1: str, index2: str | None = ...) -> str: ...
    def insert(self, index: str, text: str, tags: str | tuple[str, ...] | None = ...) -> None: ...
    def delete(self, index1: str, index2: str | None = ...) -> None: ...

class CTkOptionMenu(CTkBaseClass):
    """CustomTkinter option menu (dropdown)."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        button_color: str | tuple[str, str] | None = ...,
        button_hover_color: str | tuple[str, str] | None = ...,
        dropdown_fg_color: str | tuple[str, str] | None = ...,
        dropdown_hover_color: str | tuple[str, str] | None = ...,
        dropdown_text_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        text_color_disabled: str | tuple[str, str] | None = ...,
        font: tuple[str, int] | Any = ...,
        dropdown_font: tuple[str, int] | Any = ...,
        values: list[str] | None = ...,
        variable: Any = ...,
        state: str = ...,
        hover: bool = ...,
        command: Callable[[str], Any] | None = ...,
        dynamic_resizing: bool = ...,
        anchor: Anchor = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def set(self, value: str) -> None: ...

class CTkProgressBar(CTkBaseClass):
    """CustomTkinter progress bar."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        progress_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        mode: str = ...,
        determinate_speed: float = ...,
        indeterminate_speed: float = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def get(self) -> float: ...
    def set(self, value: float) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def step(self) -> None: ...

class CTkScrollbar(CTkBaseClass):
    """CustomTkinter scrollbar."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_spacing: int = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        button_color: str | tuple[str, str] | None = ...,
        button_hover_color: str | tuple[str, str] | None = ...,
        minimum_pixel_length: int = ...,
        orientation: str = ...,
        command: Callable[..., Any] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def set(self, first: float, last: float) -> None: ...

class CTkTabview(CTkBaseClass):
    """CustomTkinter tabview widget."""
    def __init__(
        self,
        master: Misc | None = ...,
        width: int = ...,
        height: int = ...,
        corner_radius: int | None = ...,
        border_width: int | None = ...,
        bg_color: str | tuple[str, str] = ...,
        fg_color: str | tuple[str, str] | None = ...,
        border_color: str | tuple[str, str] | None = ...,
        segmented_button_fg_color: str | tuple[str, str] | None = ...,
        segmented_button_selected_color: str | tuple[str, str] | None = ...,
        segmented_button_selected_hover_color: str | tuple[str, str] | None = ...,
        segmented_button_unselected_color: str | tuple[str, str] | None = ...,
        segmented_button_unselected_hover_color: str | tuple[str, str] | None = ...,
        text_color: str | tuple[str, str] | None = ...,
        text_color_disabled: str | tuple[str, str] | None = ...,
        command: Callable[[str], Any] | None = ...,
        state: str = ...,
        anchor: Corner = ...,
        **kwargs: Any,
    ) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def place(self, **kwargs: Any) -> None: ...
    def add(self, name: str) -> CTkFrame: ...
    def delete(self, name: str) -> None: ...
    def get(self) -> str: ...
    def set(self, name: str) -> None: ...
    def tab(self, name: str) -> CTkFrame: ...

# Utility functions
def set_appearance_mode(mode_string: Literal["Light", "Dark", "System"]) -> None: ...
def get_appearance_mode() -> Literal["Light", "Dark"]: ...
def set_default_color_theme(color_string: Literal["blue", "green", "dark-blue"] | str) -> None: ...
def set_widget_scaling(scaling_value: float) -> None: ...
def set_window_scaling(scaling_value: float) -> None: ...
def deactivate_automatic_dpi_awareness() -> None: ...
