"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Protocol, runtime_checkable

"""Type stubs for tkinter standard library (minimal coverage for RC Gestor).

This stub file provides type hints for tkinter widgets and methods that trigger
false positives in Pyright due to incomplete upstream stubs or ttkbootstrap extensions.

Created for CompatPack-15 on 2025-11-13.
"""
@runtime_checkable
class Misc(Protocol):
    """Protocol for tkinter Misc mixin."""
    def wm_transient(self, master: Misc | None = ...) -> str | None:
        ...

    def grid_bbox(self, column: int | None = ..., row: int | None = ..., col2: int | None = ..., row2: int | None = ...) -> tuple[int, int, int, int]:
        ...

    def grid_columnconfigure(self, index: int, weight: int | None = ..., minsize: int | None = ..., pad: int | None = ..., **kw: Any) -> Any:
        ...

    def grid_rowconfigure(self, index: int, weight: int | None = ..., minsize: int | None = ..., pad: int | None = ..., **kw: Any) -> Any:
        ...

    def winfo_exists(self) -> bool:
        ...

    def winfo_toplevel(self) -> Misc:
        ...

    def update_idletasks(self) -> None:
        ...

    def after(self, ms: int, func: Callable[..., Any] | None = ..., *args: Any) -> str:
        ...

    def bind(self, sequence: str, func: Callable[..., Any] | None = ..., add: str | None = ...) -> str:
        ...

    def configure(self, **kwargs: Any) -> None:
        ...

    def config(self, **kwargs: Any) -> None:
        ...

    def __getitem__(self, key: str) -> Any:
        ...

    def __setitem__(self, key: str, value: Any) -> None:
        ...



class Toplevel(Misc):
    """tkinter Toplevel window."""
    def __init__(self, master: Misc | None = ..., **kwargs: Any) -> None:
        ...

    def destroy(self) -> None:
        ...

    def title(self, string: str | None = ...) -> str | None:
        ...

    def geometry(self, newGeometry: str | None = ...) -> str | None:
        ...

    def grab_set(self) -> None:
        ...

    def grab_release(self) -> None:
        ...

    def focus_set(self) -> None:
        ...

    def protocol(self, name: str, func: Callable[[], Any] | None = ...) -> str | None:
        ...



@runtime_checkable
class Wm(Protocol):
    """Protocol for window manager methods."""
    def wm_transient(self, master: Misc | None = ...) -> str | None:
        ...

    def wm_attributes(self, *args: Any) -> Any:
        ...

    def wm_title(self, string: str | None = ...) -> str | None:
        ...

    def wm_geometry(self, newGeometry: str | None = ...) -> str | None:
        ...



class Tcl_Obj:
    """Placeholder for Tcl object type."""
    ...


class Button(Misc):
    """tkinter Button widget."""
    def __init__(self, master: Misc | None = ..., *, text: str = ..., command: Callable[[], Any] | None = ..., **kwargs: Any) -> None:
        ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def __getitem__(self, key: str) -> Any:
        ...

    def __setitem__(self, key: str, value: Any) -> None:
        ...



