"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Sequence
from tkinter import Misc

"""Type stubs for tkinter.ttk widgets (minimal coverage for RC Gestor).

This stub file extends tkinter.ttk with type hints for ttkbootstrap extensions
(bootstyle parameter) and other methods that trigger Pyright false positives.

Created for CompatPack-15 on 2025-11-13.
"""
Bootstyle = str

class Frame(Misc):
    """ttk.Frame widget with ttkbootstrap extensions."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        padding: int | tuple[int, ...] | Sequence[int] | None = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def place(self, **kwargs: Any) -> None:
        ...



class Label(Misc):
    """ttk.Label widget with ttkbootstrap extensions."""
    def __init__(self, master: Misc | None = ..., *, text: str = ..., textvariable: Any = ..., bootstyle: Bootstyle | None = ..., **kwargs: Any) -> None:
        ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def configure(self, **kwargs: Any) -> None:
        ...

    def cget(self, key: str) -> Any:
        ...



class Button(Misc):
    """ttk.Button widget with ttkbootstrap extensions."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        text: str = ...,
        command: Callable[[], Any] | None = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def configure(self, **kwargs: Any) -> None:
        ...

    def invoke(self) -> Any:
        ...



class Entry(Misc):
    """ttk.Entry widget with ttkbootstrap extensions."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        textvariable: Any = ...,
        width: int | None = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def get(self) -> str:
        ...

    def insert(self, index: int | str, string: str) -> None:
        ...

    def delete(self, first: int | str, last: int | str | None = ...) -> None:
        ...



class Combobox(Entry):
    """ttk.Combobox widget with ttkbootstrap extensions."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        textvariable: Any = ...,
        values: Sequence[str] = ...,
        state: str = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def configure(self, **kwargs: Any) -> None:
        ...

    def current(self, newindex: int | None = ...) -> int:
        ...

    def __getitem__(self, key: str) -> Any:
        ...

    def __setitem__(self, key: str, value: Any) -> None:
        ...



class Treeview(Misc):
    """ttk.Treeview widget."""
    def __init__(self, master: Misc | None = ..., *, columns: Sequence[str] = ..., show: str = ..., selectmode: str = ..., **kwargs: Any) -> None:
        ...

    def heading(self, column: str, option: str | None = ..., **kw: Any) -> Any:
        ...

    def column(self, column: str, option: str | None = ..., **kw: Any) -> Any:
        ...

    def insert(self, parent: str, index: int | str, iid: str | None = ..., **kw: Any) -> str:
        ...

    def delete(self, *items: str) -> None:
        ...

    def get_children(self, item: str | None = ...) -> tuple[str, ...]:
        ...

    def selection(self) -> tuple[str, ...]:
        ...

    def set(self, item: str, column: str, value: Any = ...) -> Any:
        ...

    def item(self, item: str, option: str | None = ..., **kw: Any) -> Any:
        ...

    def bbox(self, item: str, column: str | None = ...) -> tuple[int, int, int, int] | None:
        ...

    def yview_moveto(self, fraction: float) -> None:
        ...

    def bind(self, sequence: str, func: Callable[..., Any] | None = ..., add: str | None = ...) -> str:
        ...

    def __getitem__(self, key: str) -> Any:
        ...

    def __setitem__(self, key: str, value: Any) -> None:
        ...



class Scrollbar(Misc):
    """ttk.Scrollbar widget."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        orient: str = ...,
        command: Callable[..., Any] | None = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def set(self, first: float, last: float) -> None:
        ...

    def configure(self, command: Callable[..., Any] | None = ..., **kwargs: Any) -> None:
        ...



class Progressbar(Misc):
    """ttk.Progressbar widget."""

    def __init__(
        self,
        master: Misc | None = ...,
        *,
        orient: str = ...,
        length: int = ...,
        mode: str = ...,
        maximum: float = ...,
        value: float = ...,
        bootstyle: Bootstyle | None = ...,
        **kwargs: Any,
    ) -> None: ...

    def pack(self, **kwargs: Any) -> None:
        ...

    def grid(self, **kwargs: Any) -> None:
        ...

    def start(self, interval: int | None = ...) -> None:
        ...

    def stop(self) -> None:
        ...

    def step(self, amount: float = ...) -> None:
        ...

    def configure(self, **kwargs: Any) -> None:
        ...

    def cget(self, key: str) -> Any:
        ...

    def __setitem__(self, key: str, value: Any) -> None:
        ...

    def __getitem__(self, key: str) -> Any:
        ...



